# Generated by Django 3.1.7 on 2021-04-04 23:20

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Image'),
        ),
    ]
